# Generated by Django 2.0 on 2018-07-28 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CapitalStockAmountHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('change_date', models.DateField(blank=True)),
                ('public_date', models.DateField(blank=True, default='1970-1-1')),
                ('generated_time', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(default='', max_length=100)),
                ('num', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='ChangeHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_source', models.TextField(default='', null=True)),
                ('change_target', models.TextField(default='', null=True)),
                ('field', models.CharField(default='', max_length=20)),
                ('generated_time', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='FinanceHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('date', models.DateField(blank=True)),
                ('per_share_net_asset', models.FloatField(default=0.0)),
                ('total_asset', models.FloatField(default=0.0)),
                ('total_liabilities', models.FloatField(default=0.0)),
                ('business_income', models.FloatField(default=0.0)),
                ('net_profit', models.FloatField(default=0.0)),
                ('generated_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockAllotmentHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('public_date', models.DateField(blank=True, default='1970-1-1')),
                ('allotment_num', models.FloatField(default=0.0)),
                ('allotment_price', models.FloatField(default=0.0)),
                ('allotment_capital_base', models.FloatField(default=0.0)),
                ('exright_date', models.DateField(blank=True, default='1970-1-1')),
                ('record_date', models.DateField(blank=True, default='1970-1-1')),
                ('generated_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockBonusHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('public_date', models.DateField(blank=True, default='1970-1-1')),
                ('stock_give', models.FloatField(default=0.0)),
                ('stock_transfer', models.FloatField(default=0.0)),
                ('stock_bonus', models.FloatField(default=0.0)),
                ('status', models.BooleanField(default=False)),
                ('exright_date', models.DateField(blank=True, default='1970-1-1')),
                ('generated_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
                ('code', models.CharField(max_length=10)),
                ('stock_exchange', models.CharField(choices=[('上证交易所', '上证交易所'), ('深证交易所', '深证交易所')], max_length=16)),
                ('block', models.CharField(default='', max_length=40)),
                ('ownership', models.CharField(default='', max_length=30)),
                ('found_date', models.DateField(blank=True, null=True)),
                ('market_list_date', models.DateField(blank=True, null=True)),
                ('equity', models.FloatField(default=0.0)),
                ('price', models.FloatField(default=0.0)),
                ('status', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TradeRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('date', models.DateField(blank=True)),
                ('open_price', models.FloatField(default=0.0)),
                ('hignest_price', models.FloatField(default=0.0)),
                ('close_price', models.FloatField(default=0.0)),
                ('lowest_price', models.FloatField(default=0.0)),
                ('trade_volume', models.FloatField(default=0.0)),
                ('trade_amount', models.FloatField(default=0.0)),
                ('generated_time', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.StockInfo')),
            ],
        ),
        migrations.AddField(
            model_name='stockbonushistory',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.StockInfo'),
        ),
        migrations.AddField(
            model_name='stockallotmenthistory',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.StockInfo'),
        ),
        migrations.AddField(
            model_name='financehistory',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.StockInfo'),
        ),
        migrations.AddField(
            model_name='changehistory',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.StockInfo'),
        ),
        migrations.AddField(
            model_name='capitalstockamounthistory',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.StockInfo'),
        ),
    ]
